name: Populate GitHub PR number in Changelog
on: [pull_request_target]
jobs:
  Populate-Changelog-Action:
    runs-on: ubuntu-20.04
    steps:
      - name: Update PR number
        uses: tarides/pr-number-action@v1.1
